### ISSUE TITLE
shows 0 for all sums

### ISSUE THREAD

**Issue by QamarMehtab** [clupascu/GoogleApps_SumByColor#4]
I have been using these functions for quite some time. Today the functions are behaving inappropriately and shows 0 for all the sums even for my older sheets. Not sure if this is because of some updates from google sheets or what...

**Comment by clupasq** [comment]
@QamarMehtab I just tested and the scripts still work fine for me. Can you share a sheet where you observed the incorrect behavior?

**Comment by QamarMehtab** [comment]
@wolfascu Thanks for your response. Yes now its working for me also. I think I found the issue as well. The script fails and returns 0 if the script is used on medium sized data running almost 50 times at once i.e. when sheet is loaded initially.

**Comment by clupasq** [comment]
@QamarMehtab Yes, in that situation it's likely that you will encounter a timeout. Unfortunately, there's no way to fix that (that I know of).
