### ISSUE TITLE
countWhereBackgroundColorIs ?

### ISSUE THREAD

**Issue by oneezy** [clupascu/GoogleApps_SumByColor#5]
Is there a way to count `background` or `foreground` cells with your script? 

Like a few others that created issues, i was under the impression that it would add the total of cells w/ the specified color given (without a number present or not).

-----

**I'm looking for something like this:**

`countWhereBackgroundColorIs(<color>, <range specification>, [<spreadsheet key>])`
or
`countWhereForegroundColorIs(<color>, <range specification>, [<spreadsheet key>])`

**Comment by oneezy** [comment]
I found this [script ](http://webapps.stackexchange.com/questions/23881/google-spreadsheet-calculating-shaded-cells/25846#25846),, did you write both of these??

```
function countWhereBackgroundColorIs(color, rangeSpecification) {
  
  var sheet = SpreadsheetApp.getActiveSpreadsheet();
  var range = sheet.getRange(rangeSpecification);
  
  var x = 0;
  
  for (var i = 1; i <= range.getNumRows(); i++) {
    for (var j = 1; j <= range.getNumColumns(); j++) {
      
      var cell = range.getCell(i, j);
      
      if(cell.getBackgroundColor() == color)
        x++;
    }
  }
  
  return x;
}
```

**Comment by clupasq** [comment]
@oneezy Yes, I've written that code. It was adapted to answer that specific question and I forgot to add it here.

Feel free to use it if it solves your problem.
